spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

bcrypt:
  salt: NpWcp6j5sCkczqPx

file:
  extension: .jar

tmp:
  dir: /tmp/easeci/registry

endpoints:
  opened:
    - "/"
    - "/performers"
    - "/performers/**"
    - "/development"
    - "/documentation/**"
    - "/api/v1/**"
