spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

bcrypt:
  salt: NpWcp6j5sCkczqPx

file:
  extension: .jar

upload:
  token:
    quantity-per-day: 5

tmp:
  dir: /tmp/easeci/registry

activation:
  url: http://easeci.io:8080/activation?activationToken=

endpoints:
  opened:
    - "/"
    - "/registration"
    - "/activation"
    - "/performers"
    - "/performers/**"
    - "/development"
    - "/documentation/**"
    - "/api/v1/**"
